In [3]:
import numpy as np

In [10]:
import matplotlib.pyplot as plt 

In [ ]:
np.random.seed(42)

In [5]:
n_records = 50 

In [6]:
products = np.random.choice(['P1','P2','P3','P4','P5'],n_records)

In [7]:
regions = np.random.choice(['NORTH','SOUTH','WEST','EAST'],n_records)

In [8]:
unit_sold = np.random.randint(1,100,n_records)

In [9]:
unit_price = np.random.uniform(10,100,n_records)

In [11]:
total_sale = unit_sold*unit_price 

In [23]:
nan_indices = np.random.choice(n_records , size = int(0.05*n_records), replace = False)

In [24]:
unit_price[nan_indices] = np.nan

In [25]:
unit_sold = unit_sold.astype(float)

In [26]:
unit_sold[nan_indices] = np.nan

In [27]:
unit_sold[np.isnan(unit_sold)] = np.nanmean(unit_sold)

In [28]:
unit_price[np.isnan(unit_price)] = np.nanmean(unit_price)

In [30]:
total_sale = unit_sold * unit_price

In [31]:
print(total_sale)

[3054.14468899 2410.05606971 2941.80383312 1535.67677623 1795.07675907
 1590.89566289 1560.10624059 2044.57189773 2308.75104425  847.58264424
 1952.90062389 2308.75104425 3847.30437394 4932.01279754 2474.15697178
 5809.89771671  730.5812969  3384.62953516   70.28319819 1120.22730066
 1247.9596645  2823.26588405  695.33961799 3057.27477854  138.83229625
 5148.4572179  1465.60428045 7972.50471565 5105.50464804   38.9509891
 1669.31824751 2821.4649256  3278.44128591 1834.28006312  453.21031866
  358.11683489 2316.46841813 2240.37954227  180.62395331 1137.9173929
 9462.10880879 1740.96498432 1929.88925598  243.57473829 1784.84325645
 1997.33323487 2671.85736244 1772.40904871 1598.05309483 2410.05606971]


In [34]:
numeric_data = np.column_stack((unit_sold,unit_price,total_sale))

In [35]:
ta

[[3.20000000e+01 9.54420215e+01 3.05414469e+03]
 [4.52873264e+01 5.32170093e+01 2.41005607e+03]
 [6.70000000e+01 4.39075199e+01 2.94180383e+03]
 [9.20000000e+01 1.66921389e+01 1.53567678e+03]
 [4.80000000e+01 3.73974325e+01 1.79507676e+03]
 [7.30000000e+01 2.17930913e+01 1.59089566e+03]
 [3.60000000e+01 4.33362845e+01 1.56010624e+03]
 [8.80000000e+01 2.32337716e+01 2.04457190e+03]
 [4.38958333e+01 5.25961320e+01 2.30875104e+03]
 [2.60000000e+01 3.25993325e+01 8.47582644e+02]
 [4.90000000e+01 3.98551148e+01 1.95290062e+03]
 [4.38958333e+01 5.25961320e+01 2.30875104e+03]
 [4.20000000e+01 9.16024851e+01 3.84730437e+03]
 [8.40000000e+01 5.87144381e+01 4.93201280e+03]
 [9.20000000e+01 2.68930106e+01 2.47415697e+03]
 [6.40000000e+01 9.07796518e+01 5.80989772e+03]
 [1.60000000e+01 4.56613311e+01 7.30581297e+02]
 [5.00000000e+01 6.76925907e+01 3.38462954e+03]
 [1.00000000e+00 7.02831982e+01 7.02831982e+01]
 [2.70000000e+01 4.14899000e+01 1.12022730e+03]
 [1.40000000e+01 8.91399760e+01 1.247959